clusterName: demo
opentelemetry-operator:
  enabled: true
defaultCRConfig:
  presets:
    otlpExporter:
      enabled: true
      endpoint: ingest.example.com:443
      headers:
        "access-token": "${ACCESS_TOKEN}"
collectors:
  daemon:
    env:
      - name: ACCESS_TOKEN
        valueFrom:
          secretKeyRef:
            key: access_token
            name: otel-collector-secret
  cluster:
    env:
      - name: ACCESS_TOKEN
        valueFrom:
          secretKeyRef:
            key: access_token
            name: otel-collector-secret

instrumentation:
  enabled: true
  env:
    - name: OTEL_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  exporter:
    endpoint: http://${OTEL_K8S_NODE_NAME}:4317
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://${OTEL_K8S_NODE_NAME}:4318
opAMPBridge:
  enabled: true
  addReportingLabel: true
