apiVersion: v2
name: opentelemetry-operator-crds
version: 0.0.1
description: |
  This chart contains only the CRDs needed for installation for the opentelemetry operator
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-operator
maintainers:
  - name: jaronoff97
icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
appVersion: 0.100.0
