{{- if .Values.clusterRole.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opentelemetry-collector.clusterRoleName" . }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - nodes/proxy
  - nodes/metrics
  - nodes/stats
  - services
  - endpoints
  - pods
  - events
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - servicemonitors
  - podmonitors
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
{{- if $.Values.clusterRole.rules }}
{{ toYaml $.Values.clusterRole.rules }}
{{- end }}
{{ range $_, $collector := $.Values.collectors -}}
{{- if $collector.config.receivers.k8s_cluster }}
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - pods
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
{{- end }}
{{- end }}
{{- end }}

{{ range $_, $collector := $.Values.collectors -}}
{{- $collector := (mergeOverwrite (deepCopy $.Values.defaultCollectorConfig) $collector) }}
{{- if and $collector.enabled $collector.clusterRoleBinding.enabled -}}
{{- $merged := (dict "Chart" $.Chart "clusterRole" $.Values.clusterRole "collector" $collector "Release" $.Release "fullnameOverride" $.Values.fullnameOverride) }}
{{- $fullname := (include "opentelemetry-collector.fullname" $merged) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ default (include "opentelemetry-collector.clusterRoleName" $) $collector.clusterRoleBinding.clusterRoleName }}
subjects:
- kind: ServiceAccount
  # quirk of the Operator
{{- if $collector.serviceAccount }}
  name: "{{ $collector.serviceAccount }}"
{{- else }}
  name: "{{ $fullname }}-collector"
{{- end }}
  namespace: {{ $.Release.Namespace }}
{{- if eq $collector.mode "statefulset" }}
- kind: ServiceAccount
{{- if $collector.targetAllocator.serviceAccount }}
  name: "{{ $collector.targetAllocator.serviceAccount }}"
{{- else }}
  name: {{ $fullname }}-targetallocator
{{- end }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- if and $.Values.opAMPBridge.enabled $.Values.bridgeClusterRole.enabled }}
{{- $merged := (dict "Chart" $.Chart "clusterRole" $.Values.clusterRole "opAMPBridge" $.Values.opAMPBridge "Release" $.Release "fullnameOverride" $.Values.fullnameOverride) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opentelemetry-opamp-bridge.clusterRoleName" . }}
rules:
  - apiGroups:
      - opentelemetry.io
    resources:
      - opentelemetrycollectors
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - 'list'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opentelemetry-opamp-bridge.fullname" $merged }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "opentelemetry-opamp-bridge.clusterRoleName" . }}"
subjects:
  - kind: ServiceAccount
    # quirk of the Operator
    {{- if $.Values.opAMPBridge.serviceAccount }}
    name: "{{ $.Values.opAMPBridge.serviceAccount }}"
    {{- else }}
    name: "{{ (include "opentelemetry-opamp-bridge.fullname" $merged) }}-bridge-opamp-bridge"
    {{- end }}
    namespace: "{{ $.Release.Namespace }}"
{{- end }}
