{{- if .Values.collector.enabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  managementState: {{ .Values.collector.managementState }}
  mode: {{ .Values.collector.mode }}
  config: |
    {{- toYaml .Values.collector.config | nindent 4 }}
  {{- if .Values.collector.replicas }}
  replicas: {{ .Values.collector.replicas }}
  {{- end }}
  {{- if .Values.collector.serviceAccount }}
  serviceAccount: {{ .Values.collector.serviceAccount }}
  {{- end }}
  {{- if .Values.collector.image }}
  image: {{ .Values.collector.image }}
  {{- end }}
  {{- if .Values.collector.upgradeStrategy }}
  upgradeStrategy: {{ .Values.collector.upgradeStrategy }}
  {{- end }}
  {{- if .Values.collector.imagePullPolicy }}
  imagePullPolicy: {{ .Values.collector.imagePullPolicy }}
  {{- end }}
  {{- if .Values.collector.hostNetwork }}
  hostNetwork: {{ .Values.collector.hostNetwork }}
  {{- end }}
  {{- if .Values.collector.shareProcessNamespace }}
  shareProcessNamespace: {{ .Values.collector.shareProcessNamespace }}
  {{- end }}
  {{- if .Values.collector.priorityClassName }}
  priorityClassName: {{ .Values.collector.priorityClassName }}
  {{- end }}
  {{- if .Values.collector.terminationGracePeriodSeconds }}
  terminationGracePeriodSeconds: {{ .Values.collector.terminationGracePeriodSeconds }}
  {{- end }}
  {{- with .Values.collector.resources }}
  resources:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.nodeSelector }}
  nodeSelector:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.args }}
  args:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.autoscaler }}
  autoscaler:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.podDisruptionBudget }}
  podDisruptionBudget:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.securityContext }}
  securityContext:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.podSecurityContext }}
  podSecurityContext:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.podAnnotations }}
  podAnnotations:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.targetAllocator }}
  targetAllocator:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.ingress }}
  ingress:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.affinity }}
  affinity:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.lifecycle }}
  lifecycle:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.livenessProbe }}
  livenessProbe:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.observability }}
  observability:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.updateStrategy }}
  updateStrategy:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .Values.collector.deploymentUpdateStrategy }}
  deploymentUpdateStrategy:
  	{{- toYaml . | nindent 4}}
  {{- end }}
  {{- if .Values.collector.volumeMounts }}
  volumeMounts:
  {{- with .Values.collector.volumeMounts }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.ports }}
  ports:
  {{- with .Values.collector.ports }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  env:
  - name: OTEL_K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: OTEL_K8S_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: OTEL_K8S_POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  - name: OTEL_K8S_POD_UID
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.uid
  - name: OTEL_K8S_POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "k8s.cluster.name={{ $.Values.clusterName }}"
  {{- with .Values.collector.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.collector.envFrom }}
  envFrom:
  {{- with .Values.collector.envFrom }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- with .Values.collector.volumeClaimTemplates }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.tolerations }}
  tolerations:
  {{- with .Values.collector.tolerations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.volumes }}
  volumes:
  {{- with .Values.collector.volumes }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.initContainers }}
  initContainers:
  {{- with .Values.collector.initContainers }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.additionalContainers }}
  additionalContainers:
  {{- with .Values.collector.additionalContainers }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.topologySpreadConstraints }}
  topologySpreadConstraints:
  {{- with .Values.collector.topologySpreadConstraints }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.collector.configmaps }}
  configmaps:
  {{- with .Values.collector.configmaps }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
