apiVersion: v2
name: kube-otel-stack
description: Chart for sending Kubernetes metrics to Lightstep using the OpenTelemetry Operator.
type: application
version: 0.2.11
appVersion: 0.73.0
dependencies:
- name: opentelemetry-operator
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.15.0
- name: kube-state-metrics
  version: "4.20.2"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: kubeStateMetrics.enabled
- name: prometheus-node-exporter
  version: "4.3.0"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: nodeExporter.enabled
