{{- if and .Values.kubeControllerManager.enabled .Values.kubeControllerManager.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "kube-otel-stack.fullname" . }}-kube-controller-manager
  labels:
    app: {{ template "kube-otel-stack.name" . }}-kube-controller-manager
    k8s-app: kube-controller-manager
{{ include "kube-otel-stack.labels" . | indent 4 }}
  namespace: kube-system
subsets:
  - addresses:
      {{- range .Values.kubeControllerManager.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        {{- $kubeControllerManagerDefaultInsecurePort := 10252 }}
        {{- $kubeControllerManagerDefaultSecurePort := 10257 }}
        port: {{ include "kube-otel-stack.kubeControllerManager.insecureScrape" (list . $kubeControllerManagerDefaultInsecurePort $kubeControllerManagerDefaultSecurePort .Values.kubeControllerManager.service.port) }}
        protocol: TCP
{{- end }}
