{{- if and .Values.kubeScheduler.enabled .Values.kubeScheduler.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-otel-stack.fullname" . }}-kube-scheduler
  labels:
    app: {{ template "kube-otel-stack.name" . }}-kube-scheduler
    jobLabel: kube-scheduler
{{ include "kube-otel-stack.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      {{- $kubeSchedulerDefaultInsecurePort := 10251 }}
      {{- $kubeSchedulerDefaultSecurePort := 10259 }}
      port: {{ include "kube-otel-stack.kubeScheduler.insecureScrape" (list . $kubeSchedulerDefaultInsecurePort $kubeSchedulerDefaultSecurePort .Values.kubeScheduler.service.port)  }}
      protocol: TCP
      targetPort: {{ include "kube-otel-stack.kubeScheduler.insecureScrape" (list . $kubeSchedulerDefaultInsecurePort $kubeSchedulerDefaultSecurePort .Values.kubeScheduler.service.targetPort)  }}
{{- if .Values.kubeScheduler.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeScheduler.service.selector }}
{{ toYaml .Values.kubeScheduler.service.selector | indent 4 }}
    {{- else}}
    component: kube-scheduler
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
